apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otus-msa-hw2.fullname" . }}
  labels:
    {{- include "otus-msa-hw2.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "otus-msa-hw2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otus-msa-hw2.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /probe/live
              port: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /probe/ready
              port: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
